{{- if .Values.remoteServer.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-manager"
  labels:
    app.kubernetes.io/name: "redskyops"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  REDSKY_SERVER_IDENTIFIER: "{{ .Values.remoteServer.identifier | b64enc }}"
  REDSKY_SERVER_ISSUER: "{{ .Values.remoteServer.issuer | b64enc }}"
  REDSKY_AUTHORIZATION_CLIENT_ID: "{{ .Values.remoteServer.clientID | b64enc }}"
  REDSKY_AUTHORIZATION_CLIENT_SECRET: "{{ .Values.remoteServer.clientSecret | b64enc }}"
{{- end -}}
